## Распознавание эмоций по тексту
Датасет был найден на сайте Kaggle. Ссылка на датасет - https://www.kaggle.com/datasets/shreejitcheela/text-emotion-recognition

In [1]:
import numpy as np
import pandas as pd

## Загрузка датасета

In [4]:
full_data_path = fr"DataBases\text_emotions\Text_Emotion.csv"

In [5]:
full_df = pd.read_csv(full_data_path)
full_df

                                                     text emotion
0       carefully word blog posts amount criticism hea...      ☹️
1       cannot remember little mermaid feeling carefre...       🙂
2       not feeling super well turns cold knocked next...       🙂
3                 feel honored part group amazing talents       🙂
4       think helping also began feel pretty lonely lo...      ☹️
...                                                   ...     ...
282817  feel honored motivated share world life changi...       🙂
282818                  feel like gloaty really delighted       🙂
282819  feel little energetic one day next several day...       🙂
282820  feel work experience fell although fantastic o...       🙂
282821  feel generous mood may give another fan fictio...       🙂

[282822 rows x 2 columns]

In [7]:
full_df[full_df.loc[:, ['emotion']] == '☹️'] = 0
full_df[full_df.loc[:, ['emotion']] == '🙂'] = 1
full_df

                                                     text emotion
0       carefully word blog posts amount criticism hea...       0
1       cannot remember little mermaid feeling carefre...       1
2       not feeling super well turns cold knocked next...       1
3                 feel honored part group amazing talents       1
4       think helping also began feel pretty lonely lo...       0
...                                                   ...     ...
282817  feel honored motivated share world life changi...       1
282818                  feel like gloaty really delighted       1
282819  feel little energetic one day next several day...       1
282820  feel work experience fell although fantastic o...       1
282821  feel generous mood may give another fan fictio...       1

[282822 rows x 2 columns]

In [ ]:
full_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 282822 entries, 0 to 282821
Data columns (total 2 columns):
 #   Column   Non-Null Count   Dtype
---  ------   --------------   -----
 0   text     282822 non-null  object
 1   emotion  282822 non-null  object
dtypes: object(2)
memory usage: 4.3+ MB

In [10]:
full_df.emotion = full_df.emotion.astype('Int8')
full_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 282822 entries, 0 to 282821
Data columns (total 2 columns):
 #   Column   Non-Null Count   Dtype
---  ------   --------------   -----
 0   text     282822 non-null  object
 1   emotion  282822 non-null  Int8
dtypes: Int8(1), object(1)
memory usage: 2.7+ MB

In [11]:
full_df.isna().sum()  # нет Nan значений, что было показано при выводе info

text       0
emotion    0
dtype: int64

In [14]:
# примеры текста отрицательных эмоций
for true_value in full_df[full_df.emotion == 0].sample(5)['text']:
    print(true_value)

remember feeling depressed seven eight
feeling dull mid ohio new hampshire may opposite
used feel rejected nobody worthless living creature not worthy love anything similar
shit shit not mean dall asleep wanted not know tired not late last night
really really sick trying act happy normal unaffected actl feel horrible inside okay

In [16]:
# примеры текста положительных эмоций
for true_value in full_df[full_df.emotion == 1].sample(5)['text'].head(5):
    print(true_value)

feel like not gracious person
said would not cry anymore not strength feel determined not cry
feel fabulous free ready th year
feel like theperson not quite sincere honest set point way impressing people
drive days none feeling feeling relieved emptiness

Предложения не похожи на написанные человеком. Они не являются полноценными. Слова идут обрывками и полный смысл предложения не понятен.